language: node_js
node_js:
  - '9.5.0'
  - '6.11.1'
branches:
  only:
  - master
  - "/^v?[0-9\\.]+/"
before_script:
  - npm --prefix functions/ install
  - npm --prefix functions/ test
script:
  - npm test
